### ISSUE TITLE
it does not work when the collection has folders in it

### ISSUE THREAD

**Issue by clarkwang** [matthewlein/postman-collection-sorter#1]
See this simple example:

```
$ jq < foo.json
{
  "info": {
    "_postman_id": "b70ffa70-8c24-4ed8-a949-34dc03b2a8e4",
    "name": "New Collection",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "New Folder",
      "item": [
        {
          "name": "New Request",
          "request": {
            "auth": {
              "type": "basic",
              "basic": [
                {
                  "key": "password",
                  "value": "123456",
                  "type": "string"
                },
                {
                  "key": "username",
                  "value": "root",
                  "type": "string"
                }
              ]
            },
            "method": "GET",
            "header": [],
            "url": {
              "raw": "http://www.foo.com/",
              "protocol": "http",
              "host": [
                "www",
                "foo",
                "com"
              ],
              "path": [
                ""
              ]
            }
          },
          "response": []
        }
      ]
    }
  ]
}
$ npx @matthewlein/postman-collection-sorter foo.json
npx: installed 2 in 2.007s
Sorting collection file:  foo.json
Cannot read property 'method' of undefined
```

**Comment by matthewlein** [comment]
Thanks for noting that. I had no idea there were folders in collections, I just use a flat huge list. And I suppose folders can have folders can have folders...

One of the rare times that recursion seems like the best option.

I'll give it a try some time.

**Comment by matthewlein** [comment]
I think this will work now for infinite levels of folders.

**Comment by clarkwang** [comment]
> I think this will work now for infinite levels of folders.

Just tried and it works fine.  Thanks!

Another thing: Could it sort the requests/folders in a case-insensitive way by default? I don't know others but I myself am not using uppercase/lowercase in a consistent way. :)

**Comment by matthewlein** [comment]
Yes, I agree case insensitive makes sense. Just updated to change that now. It sorts by name lowercased, so casing will not matter.

**Comment by clarkwang** [comment]
Just tried but case insensitive sorting does not work for me (tested with `folders.postman_collection.json` in the git repo):

~~~
$ git log --oneline
edb7a32 (HEAD -> master, origin/master, origin/HEAD) case insensitive sorting
39d8255 recursively sort folders
df951d7 add folders json
[...]
$ npx @matthewlein/postman-collection-sorter folders.postman_collection.json
npx: installed 2 in 2.306s
Sorting collection file:  folders.postman_collection.json
Sorting Successful!
Sorted collection saved to: folders.postman_collection.sorted.json
$ jq -C '.item[].name' < folders.postman_collection.sorted.json 
"Animals"
"Auth"
"Bikes"
"Fruit"
"auth"
"bikes"
"users"
$
~~~

I know nothing about `npx`. Do I need to wait some time for the script to be published somewhere online?

**Comment by matthewlein** [comment]
Sorry, I forgot to build before publish. I don't have a great automated process.

`npm` is pretty much instant publish. `npx` is a download and run version of `npm` so you don't have to have it downloaded and maintained on your machine. https://www.npmjs.com/package/npx

**Comment by clarkwang** [comment]
It works now. Thanks a lot.
